- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Include Variables
      include_vars:
        file: vpc_setup.txt
          - name: Create VPC
    
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        state: present
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: {{ state }}
        tags:
          Name: "{{ vpc_name }}"
      register: vpcout

    - name: Print VPC ID
      debug:
        var: vpcout.vpc.id

    # - name: Create Subnet
    #   ec2_vpc_subnet:
    #     vpc_id: "{{ vpc.vpc.id }}"
    #     cidr: "{{ subnet_cidr_block }}"
    #     az: "{{ availability_zone }}"
    #     state: present
    #     tags:
    #       Name: "{{ subnet_name }}"
    #   register: subnet

    # - name: Print Subnet ID
    #   debug:
    #     var: subnet.subnet.id

    # - name: Create Internet Gateway
    #   ec2_vpc_igw:
    #     vpc_id: "{{ vpc.vpc.id }}"
    #     state: present
    #     tags:
    #       Name: "{{ igw_name }}"
    #   register: igw

    # - name: Print Internet Gateway ID
    #   debug:
    #     var: igw.gateway_id

    # - name: Attach Internet Gateway to VPC
    #   ec2_vpc_igw:
    #     vpc_id: "{{ vpc.vpc.id }}"
    #     gateway_id: "{{ igw.gateway_id }}"
    #     state: present

    # - name: Create Route Table
    #   ec2_vpc_route_table:
    #     vpc_id: "{{ vpc.vpc.id }}"
    #     state: present
    #     tags:
    #       Name: "{{ route_table_name }}"
    #   register: route_table

    # - name: Print Route Table ID
    #   debug:
    #     var: route_table.route_table.id

    # - name: Create Route
    #   ec2_vpc_route_table:
    #     vpc_id: "{{ vpc.vpc.id }}"
    #     route_table_id: "{{ route_table.route_table.id }}"
    #     dest: